#Collaborative Workflow
name: #Collaborative Workflow

on:
  push:
    branches:
      - main

jobs:
    update_html_and_readme:
      runs-on: ubuntu-latest

      steps:
        # Step 1: Checkout repo
        - name: Checkout Repository
          uses: actions/checkout@v3

        #Step 2: Update index.html
        - name: Update HTML
          run: 
            # Team Leader Update index.html
            if [ "$ {{ github.actor }}" == "xJessD" ]; then
              sed -i '/<\/body>/i <p>Updated by Team Leader on '"$(date)"'</p>' index.html
            fi

        # Step 3: Update README
        - name: Update README
          run: 
            echo "### Updated by ${{ github.actor }} on $(date '+%Y-%m-%d %H:%M:%S') [Commit: $(git rev-parse --short HEAD)]" >> README.md

        # Step 4: Commit changes back to the repository
        - name: Commit and push changes
          run: 
            - git config --global user.name "github-actions[bot]"
            - git config --global user.email "github-actions[bot]@users.noreply.github.com"
            - git add .
            - git commit -m "Workflow: Updated HTML and README for ${{ github.actor }}" || echo "No changes to commit"
            - git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            - git push origin main
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
